name: notify telegram
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: notify telegram
        uses: yanzay/notify-telegram@v0.1.0
        if: always()
        with:
          chat: ${{ secrets.CHAT_ID }}
          token: ${{ secrets.BOT_TOKEN }}
          status: ${{ job.status }}
